"""Position-ID A1 migration · CEO 2026-08-31 authorization.

Legacy PIDs in `reports/telegram/aegis_history.xlsx` column "Position ID"
use the runner-agnostic form `TICKER_MKT_YYYYMMDD` (e.g.
`LUPIN_IND_20260731`). New PIDs generated by
`backend.research.opportunity_registry.make_opportunity_id` use the
runner-inclusive form `MKT-RUNNER-TICKER-YYYYMMDD-hash6` (e.g.
`IND-R1-LUPIN-20260731-abc123`). Mixed generations mean the same
runner-agnostic PID appears in both R1 and R2 rows on the same date,
violating the audit-uniqueness contract (Definitions sheet: "one row
per (position_id, snapshot_date)").

CEO decision A1: make Position ID runner-specific at source.

## Migration rule (deterministic · stop-on-ambiguous)

For every source-XLSX row where `Position ID` matches the legacy
pattern:

  1. Take the row's own `Run_Type` value.
  2. If Run_Type is empty / not in {R1, R2, SHADOW, MOMENTUM} → STOP
     and emit the row to `reports/migration/ambiguous_pids_YYYYMMDD.jsonl`
     for manual resolution. Do NOT guess.
  3. Extract ticker + market + date from the legacy PID components.
     If parse fails → STOP (as above).
  4. Compute new PID = make_opportunity_id(market, runner, ticker,
     created_date).
  5. Update the row's `Position ID` cell to the new PID · move the
     legacy value to `Legacy Position ID` (col 3) if that column exists
     and is currently empty.

## Safety

- ALL source files backed up to
  `reports/backup/pre_pid_migration_20260831/` before this script runs
  (see backup step in the outer procedure).
- On ANY ambiguity: exit non-zero, emit the ambiguous rows to a
  dedicated file, DO NOT write any partial migration.
- Idempotent: rows already in new format are skipped.
- Historical rows preserved: no deletion, no dedup.

## Not touched by this script

- backend.research.opportunity_registry (Registry decision logic ·
  LOCKED · make_opportunity_id already produces new-format IDs)
- R1 / R2 / E1 / E2 / E3 / trading logic (LOCKED)
- Snapshot ledger (uses a different identifier system · prediction_id
  is MKT-TICKER-DATE-hash · runner is in `canonical_signal` field ·
  runs orthogonal to opportunity_id)
- Any XLSX cell other than Position ID and Legacy Position ID columns
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT))

from backend.research.opportunity_registry import make_opportunity_id  # noqa: E402


_LEGACY_PID_RE = re.compile(r"^([A-Z][A-Z0-9]*)_([A-Z]{3})_(\d{8})$")
_NEW_PID_PREFIXES = ("IND-", "USA-", "R1-", "R2-", "SHADOW-", "MOMENTUM-")
_VALID_RUNNERS = {"R1", "R2", "SHADOW", "MOMENTUM"}
_MARKET_FROM_TAG = {"IND": "india", "USA": "usa"}


def _is_legacy_pid(pid: str) -> bool:
    if not pid: return False
    if pid.startswith(_NEW_PID_PREFIXES): return False
    return bool(_LEGACY_PID_RE.match(pid))


def _parse_legacy_pid(pid: str) -> tuple[str, str, str] | None:
    """Return (ticker, market_tag, YYYYMMDD) or None if unparseable."""
    m = _LEGACY_PID_RE.match(pid or "")
    if not m: return None
    return m.group(1), m.group(2), m.group(3)


def _yyyymmdd_to_iso(ds: str) -> str:
    return f"{ds[:4]}-{ds[4:6]}-{ds[6:8]}"


def migrate(xlsx_path: Path, report_path: Path, ambiguous_path: Path) -> int:
    """Return exit code · 0 on clean success · 2 on ambiguity · 1 on error."""
    from openpyxl import load_workbook
    wb = load_workbook(xlsx_path)
    if "AEGIS Daily" not in wb.sheetnames:
        print(f"[migrate:pid-a1] '{xlsx_path.name}' has no 'AEGIS Daily' sheet",
              file=sys.stderr)
        return 1
    ws = wb["AEGIS Daily"]

    hdr = [c.value for c in ws[1]]
    def _col(name: str) -> int | None:
        for i, v in enumerate(hdr):
            if v and str(v).strip().lower() == name.lower():
                return i + 1
        return None

    c_pid = _col("Position ID")
    c_legacy = _col("Legacy Position ID")
    c_run = _col("Run_Type") or _col("Runner")
    c_country = _col("Country")
    c_date = _col("Date")
    if not c_pid or not c_run:
        print(f"[migrate:pid-a1] required columns missing · "
              f"Position ID={c_pid} · Run_Type={c_run}", file=sys.stderr)
        return 1

    n_total = 0
    n_new_already = 0
    n_migrated = 0
    n_skipped_empty = 0
    ambiguous_rows: list = []
    remap_stats: dict = {}

    for r_idx in range(2, ws.max_row + 1):
        n_total += 1
        pid_cell = ws.cell(r_idx, c_pid)
        pid_v = str(pid_cell.value or "")
        if not pid_v:
            n_skipped_empty += 1
            continue
        if pid_v.startswith(_NEW_PID_PREFIXES):
            n_new_already += 1
            continue
        if not _is_legacy_pid(pid_v):
            ambiguous_rows.append({
                "row": r_idx, "pid": pid_v, "reason": "unrecognized PID format",
                "runner": str(ws.cell(r_idx, c_run).value or ""),
                "date": str(ws.cell(r_idx, c_date).value or "") if c_date else "",
                "country": str(ws.cell(r_idx, c_country).value or "") if c_country else "",
            })
            continue
        # Row runner
        run_v = str(ws.cell(r_idx, c_run).value or "").upper().replace("_NEW", "").strip()
        if run_v not in _VALID_RUNNERS:
            ambiguous_rows.append({
                "row": r_idx, "pid": pid_v,
                "reason": f"runner not in valid set · got '{run_v}'",
                "runner": run_v,
            })
            continue
        parsed = _parse_legacy_pid(pid_v)
        if not parsed:
            ambiguous_rows.append({
                "row": r_idx, "pid": pid_v, "reason": "unparseable legacy PID",
            })
            continue
        ticker, mkt_tag, ds = parsed
        market_name = _MARKET_FROM_TAG.get(mkt_tag)
        if not market_name:
            ambiguous_rows.append({
                "row": r_idx, "pid": pid_v, "reason": f"unknown market tag '{mkt_tag}'",
            })
            continue
        # Cross-check with row's Country column when available
        if c_country:
            country_v = str(ws.cell(r_idx, c_country).value or "").lower()
            if country_v and country_v != market_name:
                ambiguous_rows.append({
                    "row": r_idx, "pid": pid_v,
                    "reason": f"PID market '{mkt_tag}' ≠ row Country '{country_v}'",
                })
                continue
        # Compute new PID
        new_pid = make_opportunity_id(
            market=market_name, runner=run_v, ticker=ticker,
            created_date=_yyyymmdd_to_iso(ds))
        # Update cells
        pid_cell.value = new_pid
        if c_legacy and not ws.cell(r_idx, c_legacy).value:
            ws.cell(r_idx, c_legacy).value = pid_v
        n_migrated += 1
        # Track split stats
        remap_stats.setdefault(pid_v, {}).setdefault(run_v, 0)
        remap_stats[pid_v][run_v] += 1

    # If any ambiguity · STOP · do not write · dump for manual review
    if ambiguous_rows:
        ambiguous_path.parent.mkdir(parents=True, exist_ok=True)
        with ambiguous_path.open("w", encoding="utf-8") as f:
            for row in ambiguous_rows:
                f.write(json.dumps(row, ensure_ascii=False) + "\n")
        print(f"[migrate:pid-a1] STOPPED · {len(ambiguous_rows)} ambiguous rows · "
              f"see {ambiguous_path} · no file written · manual review required",
              file=sys.stderr)
        wb.close()
        return 2

    # Success · write back
    wb.save(xlsx_path)
    wb.close()

    # Summary report
    n_split = sum(1 for runners in remap_stats.values() if len(runners) > 1)
    report = {
        "engine": "aegis.migration.position_id.a1",
        "asof": date.today().isoformat(),
        "source_file": str(xlsx_path.relative_to(_ROOT)),
        "rows_scanned": n_total,
        "rows_already_new_format": n_new_already,
        "rows_migrated": n_migrated,
        "rows_skipped_empty": n_skipped_empty,
        "distinct_legacy_pids_migrated": len(remap_stats),
        "distinct_legacy_pids_split_by_runner": n_split,
        "example_splits": [
            {"legacy_pid": pid, "per_runner_row_counts": counts}
            for pid, counts in remap_stats.items() if len(counts) > 1
        ][:10],
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False),
                            encoding="utf-8")
    print(f"[migrate:pid-a1] SUCCESS · migrated {n_migrated} rows · "
          f"{len(remap_stats)} legacy PIDs ({n_split} split into per-runner)")
    print(f"[migrate:pid-a1] report: {report_path.relative_to(_ROOT)}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--xlsx", default="reports/telegram/aegis_history.xlsx",
                     help="Source XLSX to migrate")
    ap.add_argument("--report",
                     default=f"reports/migration/pid_migration_a1_{date.today().isoformat()}.json")
    ap.add_argument("--ambiguous",
                     default=f"reports/migration/ambiguous_pids_a1_{date.today().isoformat()}.jsonl")
    args = ap.parse_args()
    xlsx_p = (_ROOT / args.xlsx).resolve()
    if not xlsx_p.exists():
        print(f"[migrate:pid-a1] source not found · {xlsx_p}", file=sys.stderr)
        return 1
    return migrate(xlsx_p,
                    (_ROOT / args.report).resolve(),
                    (_ROOT / args.ambiguous).resolve())


if __name__ == "__main__":
    sys.exit(main())
